name: default
data-dir: /path/to/data-dir
listen-client-urls: http://0.0.0.0:2379
advertise-client-urls: http://localhost:2379
listen-peer-urls: http://0.0.0.0:2380
initial-advertise-peer-urls: http://localhost:2380
initial-cluster-token: etcd-cluster
initial-cluster: default=http://localhost:2380
initial-cluster-state: new

